version: 2
jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t quipper/ansible-circleci:${CIRCLE_SHA1} .
      - run:
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
              docker push quipper/ansible-circleci:${CIRCLE_SHA1}
            fi
